vich_uploader:
    db_driver: orm

    mappings:
        cv:
            uri_prefix: /cv
            upload_destination: '%kernel.project_dir%/public/cv'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
